version: '3.8'

services:
  react-app:
    build: .
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - pnpm-store:/root/.pnpm-store
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

volumes:
  pnpm-store:
